/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'יצחק שנלר' at '19:59 20/01/18' with Gradle 2.14.1
 *
 * @author יצחק שנלר, @date 19:59 20/01/18
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
