//import org.junit.Test;
//import static org.junit.Assert.*;
//
///*
// * This Java source file was auto generated by running 'gradle init --type java-library'
// * by 'יצחק שנלר' at '19:59 20/01/18' with Gradle 2.14.1
// *
// * @author יצחק שנלר, @date 19:59 20/01/18
// */
//public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
//}
